name: publish

on: [workflow_dispatch]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-asterisk-build-asl3-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
  
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build the Asterisk Docker Image
        run: |
          export VERSION=$(cat version.txt)
          echo "Version : $VERSION"
          docker build --tag ghcr.io/mkmer/asl3-docker:$VERSION .
          docker image --tag ghcr.io/mkmer/asl3-docker:latest
          docker run ghcr.io/mkmer/asl3-docker:$VERSION
          docker push ghcr.io/mkmer/asl3-docker:$VERSION
        